modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT License"
issueTrackerURL = "https://github.com/Mrthomas20121/Aether-Gravitation/issues"

[[mods]]
modId = "gravitation"
version = "1.0.7"
displayName = "Aether Gravitation"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/gravitation"
#logoFile="tinkers_reforged_logo.png"
credits = "Aether Team"
authors = "Mrthomas20121"
description = '''
Add more content to the Aether.
'''

[[dependencies.gravitation]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.1.1,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.gravitation]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.gravitation]]
    modId = "aether"
    mandatory = true
    versionRange = "[1.0.0,)"
    ordering = "AFTER"
    side = "BOTH"